### ISSUE TITLE
Error when accessing `output_information` of an import job

### ISSUE THREAD

**Issue by tebdon-granta** [ansys/grantami-jobqueue#138]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

When doing a text import, the import job fails. My script is written to check for this by looking in the job's output_information property to see if the number of errors > 0, and if it is, to read the error message and present it to the user. However, the job object returned from the import doesn't have the output_information dictionary attached to it, and thus causes an error when I try to explore it to understand the success or otherwise of the job. I would like a sensible dictionary response in this case, to prevent a catastrophic error of my script.

Traceback (most recent call last):
  File "D:\Program_Files\Granta\Redacted\main.py", line 254, in <module>
    main()
  File "D:\Program_Files\Granta\Redacted\main.py", line 223, in main
    successes, failures = import_data(client, filepaths_to_import, TEST_DATA_TEMPLATE)
  File "D:\Program_Files\Granta\Redacted\main.py", line 152, in import_data
    if job.output_information["summary"]["NumberOfErrors"] > 0:
  File "C:\LegacyApp\Python\Python39\lib\site-packages\ansys\grantami\jobqueue\_models.py", line 1190, in output_information
    for k, v in self._job_specific_outputs.items():  # type: ignore[union-attr]
AttributeError: 'NoneType' object has no attribute 'items'

### 📝 Steps to reproduce

Break an import in just the right way.

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

MI 24R2

### 🐍 Which Python version are you using?

3.9

### 📦 Installed packages

```shell
ansys-grantami-jobqueue==1.0.1
and others...
```

**Comment by ludovicsteinbach** [comment]
Tim has kindly provided debug logs, in which we can see that the response for the job does not include the field `jobSpecificOutputs`. The property `output_information` assumes it exists and is a dictionary, resulting in the failure seen above.

The fix should be reasonably simple, we're waiting for the server logs to check why this happened in the first place, and decide how best to address this.

**Comment by ludovicsteinbach** [comment]
The root cause of this issue seems to be that the import job includes an import to a file attribute. The path of the file to import, which is included in the import data file, is a full path to a network location. Job Queue does not have sufficient permissions to access the network location and the job fails.
In this particular case, the job has a failed status and doesn't include `jobSpecificOutputs`.

**Comment by da1910** [comment]
We should be tolerant to missing `jobSpecificOutputs` as the field is nullable in that case.
