### ISSUE TITLE
OSError when a file path provided to an Importer is a URL

### ISSUE THREAD

**Issue by konradkudziagranta** [ansys/grantami-jobqueue#157]
### 🔍 Before submitting the issue

- [x] I have searched among the existing issues
- [x] I am using a Python virtual environment

### 🐞 Description of the bug

Providing path in form of [<url-str>] to any ‘file’ (template_file, data_files, combined_files, attachment_files) parameter in import request, results in error:
`“OSError: [Errno 22] Invalid argument: 'https://upload.wikimedia.org/wikipedia/en/a/a9/Example.jpg'“`

 Should we catch it a bit earlier, that this is not a valid relative path ?

### 📝 Steps to reproduce

prepare ExcelImportJobRequest where one of files parameter is an URL instead of normal local/relative path, and create a job with it

```python
import_request = jobqueue.ExcelImportJobRequest(
    name = "name",
    description = "description",
    template_file = ".\myTemplate.xls",
    data_files = ["https://upload.wikimedia.org/wikipedia/en/a/a9/Example.jpg"]
)

import_job = api_client.create_job_and_wait(job_request=import_request)
```

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

ansys-grantami-jobqueue 1.1.0rc0
ansys-grantami-serverapi-openapi 4.0.0
ansys-openapi-common 2.2.0
GRANTA_MIScriptingToolkit 4.1.75

Granta MI b. 25.1.1888

### 🐍 Which Python version are you using?

3.13

### 📦 Installed packages

```shell
ansys-grantami-jobqueue==1.1.0rc0
ansys-grantami-recordlists==1.3.0rc0
ansys-grantami-serverapi-openapi==4.0.0
ansys-openapi-common==2.2.0
certifi==2024.8.30
cffi==1.17.1
charset-normalizer==3.4.0
cryptography==43.0.3
filetype==1.2.0
GRANTA_MIScriptingToolkit @ file:///C:/Automation/STK/scripting-toolkit-4-1-75/pip/granta_miscriptingtoolkit-4.1.75-cp38-abi3-win_amd64.whl#sha256=7be8c6e46f63c29c0fde2a30911b2c3a607c5fb6443258b56e77339ca4db58b0
idna==3.10
jaraco.classes==3.4.0
jaraco.context==6.0.1
jaraco.functools==4.1.0
keyring==25.5.0
more-itertools==10.5.0
packaging==24.2
pycparser==2.22
pyparsing==3.2.0
pypiwin32==223
pyspnego==0.11.2
python-dateutil==2.9.0.post0
pywin32==308
pywin32-ctypes==0.2.3
requests==2.32.3
requests-negotiate-sspi==0.5.2
requests_ntlm==1.3.0
six==1.16.0
sspilib==0.2.0
urllib3==2.2.3
```

**Comment by Andy-Grigg** [comment]
I don't think there's anything we should do here. No where in the documentation do we state that we support URLs or http paths, all the examples and API documentation refers to files.

The underlying pathlib library doesn't do anything with URLs, so there's nothing we can do easily to assert the path _isn't_ a URL.
